### ISSUE TITLE
As a designer/developer, I want to provide other ways of triggering the feedback modal.

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/feedback-widget#11]
We would like to discuss the possibility of having alternate ways of triggering the feedback widget that don't involve the floating button that resides on the right side of the browser. Reason being that some of us feel that the button is distracting and would rather like to have the widget triggered by say a "Contact Us" link somewhere on the site like the footer perhaps.

Would this be acceptable and if so, would it require any changes to the widgets implementation?

**Comment by jordanpadams** [comment]
@anilnatha there is a bit of history here where it was indicated both by our management and the 2017 PDS Roadmap Study that we were not doing a great job of being transparent about getting input from our community, as well as showing synergy across the PDS for how someone would submit feedback or request information. The "Contact Us" link we had in our top bar (and still do) did not appear central enough to be obvious to users. the design of the button and the widget was mimicked after similar feedback buttons we saw on several popular websites at the time.

that all being said, this is all subject to change per the outcomes of PDS Web Modernization Working Group. in the meantime, if you would like to trigger the modal without the floating button, you can do so using a URL. this comes built into the feedback widget, as-is. for example:

https://atmos.nmsu.edu/?feedback=true
https://pds.nasa.gov/?feedback=true
https://pds-smallbodies.astro.umd.edu/?feedback=true

**Comment by jordanpadams** [comment]
closing as wontfix as no work is needed here.

**Comment by anilnatha** [comment]
Thanks for the information and guidance @jordanpadams . I'll relay the information to the team.
