### ISSUE TITLE
Style updates per PDS DOI UI issues

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/feedback-widget#12]
- [x] TBD to be updated by @c-suh

**Comment by c-suh** [comment]
Noticed differences when reviewing the widget's integration into the DOI UI and found more when looking at https://sbn.psi.edu/pds/ and https://pdssbn.astro.umd.edu/. Have used these three as a basis and tested the changes on pds-gamma as well as my local deployment of the DOI UI.
![Screen Shot 2021-07-12 at 6 46 32 PM](https://user-images.githubusercontent.com/18314609/125377548-0cfa2980-e342-11eb-9c58-ebaf0d533a92.png)
![Screen Shot 2021-07-12 at 6 47 29 PM](https://user-images.githubusercontent.com/18314609/125377549-0d92c000-e342-11eb-8bb7-3b885b304ac6.png)
![Screen Shot 2021-07-12 at 6 47 56 PM](https://user-images.githubusercontent.com/18314609/125377552-0d92c000-e342-11eb-9805-fb46d10d3170.png)

**Comment by c-suh** [comment]
@jordanpadams this has been merged into `main`, included in a PR for pds-doi-ui, and deployed to pds.nasa.gov.
