### ISSUE TITLE
Feedback does not let submissions through for SBN

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/feedback-widget#17]
## 🐛 Describe the bug
For SBN-UMD, a submission gives the message "Are you a bot? Suspicious behavior detected."
For SBN-PSI, a submission gives the message "Status: error; Error: Not Found"

## 📜 To Reproduce
1. Go to 
    - https://pds-smallbodies.astro.umd.edu/
    - https://pdssbn.astro.umd.edu/
    - https://sbn.psi.edu/pds/
    - https://arcnav.psi.edu/
2. Open the Feedback form by clicking the blue tab on the right side of the screen which says "Need Help?"
3. Fill in some comment and click the button to "Send Feedback"
4. See message 

## 🕵️ Expected behavior
The message should be something like, "Thank you for making the PDS a better site. If you provided an email address, a PDS representative will get back to you as soon as possible."

## 📚 Version of Software Used
?

## 🩺 Test Data / Additional context
SBN-UMD had updates to their servers, after which the widget stopped working. I do not know if this applies to SBN-PSI as well.

---

**Comment by c-suh** [comment]
For SBN-UMD, we're verifying if PHP is installed on their servers. Documentation needs to be updated (which wasn't actually done with https://github.com/NASA-PDS/feedback-widget/issues/9). 
For SBN-PSI, the recaptcha-v3-verify.php file is 404.

**Comment by c-suh** [comment]
Submission works if recaptcha is disabled, which still does not make clear if the issue is with recaptcha or PHP, since the recaptcha is the only element of the widget which utilizes PHP. Am making edits to output more clear error messages.

**Comment by acraugh** [comment]
The PSI widget isn't working either, but the message is different:
![Screenshot 2022-03-01 170604](https://user-images.githubusercontent.com/12803392/156257003-4f5ec44f-16e5-4732-a343-b273a7e3e82b.png)

Is this the symptom of an expired "secret key"?

**Comment by c-suh** [comment]
@acraugh no, that is not an expired secret key. A file is, in fact, missing. ~~I suspect this has to do with https://sbn.psi.edu having become https://sbn.psi.edu/pds at some point.~~ (Theory is crossed out because https://arcnav.psi.edu/ has the same error without the subdirectory.) @jordanpadams, who at PSI would I contact about this?

**Comment by jordanpadams** [comment]
@mdrum ☝️

**Comment by mdrum** [comment]
Apologies, yep we broke it on our end. This should be patched now on https://sbn.psi.edu/, and https://arcnav.psi.edu/ will be fixed shortly.

**Comment by jordanpadams** [comment]
@c-suh i believe this is done enough for both SBN sub-nodes for the time being?

**Comment by acraugh** [comment]
@jordanpadams , depends on what you mean by "enough". It still doesn't work at SBN UMD. I assume this is a problem with not having dependencies in place in our environment. Since the dependencies for this code are not documented, I give up. I don't have the expertise needed to derive the dependencies and it's not clear I could do anything about it if I did.

**Comment by jordanpadams** [comment]
@acraugh we can talk about this offline, and will resend the dependencies, but I am ok with UMD not using the recaptcha for now and we can revisit if it becomes an issue.

**Comment by acraugh** [comment]
@jordanpadams - sounds good, or at least good enough. 🙂 I'm reasonably confident that the problem is _not_ in the code itself, so no reason to hold it up. If and when we ever do figure out what the problem is, we can document the solution in the appropriate manner.

**Comment by c-suh** [comment]
PSI website's Feedback widget is letting submissions through to the PDS Operator. I've been in touch with Anne about disabling the recpatcha on UMD's sites but haven't heard back in the affirmative yet.

**Comment by tloubrieu-jpl** [comment]
@c-suh will send an email to @acraugh next week (on Monday)

**Comment by c-suh** [comment]
Didn't need to send the email. Just checked the widget at SBN-UMD's two sites and recaptcha has been disabled. Will need to tag a Feedback widget release.
