### ISSUE TITLE
Update documentation describing how to enable PHP on HTTP server

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/feedback-widget#9]
I followed the directions but could not get the widget to show for either:
- http://sharks.jplsoftball.org/killme1.shtml is https://pds.nasa.gov/datasearch/subscription-service/SS-20191030.shtml moved directly to the other web site.
- http://sharks.jplsoftball.org/killme2.shtml is a stripped down version that copies the code from github into its &lt;head&gt;. 

Maybe the web server is missing something, but, if so, the directions should say what the requirements are.

**Comment by jordanpadams** [comment]
@rchenatjpl did you register in advance? It won't work unless you register with the Google analytics. that being said, this has been tested and deployed several times so I'm not sure we need to build out the docs more thoroughly at this time.

**Comment by rchenatjpl** [comment]
I think there was a real problem, perhaps with versioning. I discussed this with Catherine, though I've forgotten the details. I did register. If I embedded the code straight off this page, nothing happened, but when I embedded the code taken from the source of a PDS web page like https://pds.nasa.gov/datasearch/subscription-service/SS-20191030.shtml, the widget showed.

**Comment by jordanpadams** [comment]
@c-suh can you help me understand this here and make sure we properly document/fix the issue and/or make sure the right version is deployed?

**Comment by c-suh** [comment]
@jordanpadams Will get started today.

**Comment by jordanpadams** [comment]
@c-suh great! can you also reopen and rename this issue to something more useful for a changelog based upon the issue you recognize?

**Comment by c-suh** [comment]
@jordanpadams Will do; I'll reopen first then rename when I have an idea of what's causing the problem.

**Comment by c-suh** [comment]
@jordanpadams I followed the same links as @rchenatjpl to pull this code, installed it on our test site, but haven't been able to replicate any problem. Perhaps I need an environment more similar to http://sharks.jplsoftball.org/killme*.shtml where the installation first didn't work? Please advise on the next step.

**Comment by jordanpadams** [comment]
if you cannot replicate, i imagine they do not have PHP enabled on the HTTP server. in which case, make sure we have that documented and tie to this issue, and update the title accordingly.

**Comment by rchenatjpl** [comment]
I can't replicate now either. Eh.

﻿On 11/6/19, 13:39, "Jordan Padams" <notifications@github.com> wrote:

    if you cannot replicate, i imagine they do not have PHP enabled on the HTTP server. in which case, make sure we have that documented and tie to this issue, and update the title accordingly.
    —

**Comment by jordanpadams** [comment]
Closing since issue could not be replicated
